### ISSUE TITLE
Synchronous option

### ISSUE THREAD

**Issue by knod** [vankasteelj/detect-lang#2]
Any chance of getting a synchronous method/feature/option in there? Is there a specific reason that this has to be asynchronous? I'd like to be able to pass this in as a function to be used in a module, but the module runs those functions synchronously, so it doesn't know to call a `.then` on anything.

My specific need aside, when you make one thing asynchronous it forces everything else that interacts with that thing to be made asynchronous. Like this situation, it generally doesn't give as much flexibility to the module user.

**Comment by vankasteelj** [comment]
retext is async

**Comment by knod** [comment]
Dang. Hmm. Do you know if there's a specific reason it's async? I could go to their repo and post the same request.

**Comment by vankasteelj** [comment]
I don't know how retext work at all, it's a truly complex library, but it is build with parse-latin, which is using callbacks. It's retext that does all the work really, this module is a simple wrapper and beautifies the output of retext

**Comment by knod** [comment]
I'm looking at detect-lang's code, but there's no explanation there - what exactly does retext do for detec-lang?

*Edit:* Sorry, I think I see a bit more of what it's doing. It looks like its assigning a possible language to each child, right? If so, I can see why it's integral.

*Edit 2:* Eh, it seems pretty crucial. I'll find a way to work around it.
